# Generated by Django 5.2.15 on 2026-07-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shahar ya kasbe ka naam (e.g., Katni, Jabalpur)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Kya is shahar me service live rakhni hai?')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Car Wash, Car Services, Breakdown Services', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='E.g., car_wash, car_services (Lowercase without spaces)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional overall category description', null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Top Wash, General Checkup', max_length=150)),
                ('price', models.IntegerField(default=0, help_text='Put 0 if it is a custom quote base')),
                ('time_duration', models.CharField(blank=True, help_text='E.g., 30 mins, 4 hours', max_length=50, null=True)),
                ('description', models.TextField(help_text='Detailed description of what is included')),
                ('is_custom_quote', models.BooleanField(default=False, help_text='Check this for Dent/Paint or Towing where price varies work-to-work')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='main.servicecategory')),
            ],
        ),
    ]
