# Generated by Django 5.2.15 on 2026-07-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_servicecategory_servicepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacecar',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='marketplacecar',
            name='photo_urls',
        ),
        migrations.RemoveField(
            model_name='marketplacecar',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='marketplacecar',
            name='video_urls',
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/photos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.marketplacecar')),
            ],
        ),
        migrations.CreateModel(
            name='CarVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='cars/videos/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.marketplacecar')),
            ],
        ),
    ]
