# Generated by Django 5.2.15 on 2026-07-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_marketplacecar_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopart',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='partorder',
            name='payment_status',
            field=models.CharField(default='Pending_Verification', max_length=20),
        ),
        migrations.AddField(
            model_name='partorder',
            name='transaction_id',
            field=models.CharField(default='', help_text='UPI Transaction ID / UTR', max_length=100),
        ),
        migrations.AlterField(
            model_name='autopart',
            name='compatibility',
            field=models.CharField(default='Universal', max_length=200),
        ),
        migrations.AlterField(
            model_name='autopart',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AutoPartPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parts/')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.autopart')),
            ],
        ),
    ]
