# Generated by Django 5.2.15 on 2026-07-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_autopart_photo_url_partorder_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=15)),
                ('car_make_model', models.CharField(help_text='e.g. Maruti Swift 2018 Petrol', max_length=200)),
                ('part_name', models.CharField(help_text='e.g. Left Side Headlight Assembly', max_length=200)),
                ('part_type', models.CharField(choices=[('New', 'New'), ('Used', 'Used / Second Hand'), ('Any', 'Any')], default='Any', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Part details, OEM number, etc.')),
                ('sample_photo', models.ImageField(blank=True, null=True, upload_to='part_requests/')),
                ('status', models.CharField(choices=[('Pending', 'Pending Search'), ('Arranged', 'Arranged / Contacted'), ('Unavailable', 'Not Available')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
