# Generated by Django 5.2.15 on 2026-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_partrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback',
            field=models.TextField(blank=True, help_text='Customer feedback for mechanic', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating from 1 to 5', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Broadcasting', 'Searching Mechanics (Broadcasting)'), ('Assigned', 'Assigned / Accepted'), ('Work in Progress', 'Work in Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Broadcasting', max_length=40),
        ),
    ]
